# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

# Switches
 set_property PACKAGE_PIN V17 [get_ports {Din0[0]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Din0[0]}]
 set_property PACKAGE_PIN V16 [get_ports {Din0[1]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Din0[1]}]
 set_property PACKAGE_PIN W16 [get_ports {Din0[2]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Din0[2]}]
 set_property PACKAGE_PIN W17 [get_ports {Din0[3]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Din0[3]}]
 set_property PACKAGE_PIN W15 [get_ports {Din1[0]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Din1[0]}]
 set_property PACKAGE_PIN V15 [get_ports {Din1[1]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Din1[1]}]
 set_property PACKAGE_PIN W14 [get_ports {Din1[2]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Din1[2]}]
 set_property PACKAGE_PIN W13 [get_ports {Din1[3]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Din1[3]}]
 set_property PACKAGE_PIN V2 [get_ports {Sel[0]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Sel[0]}]
 set_property PACKAGE_PIN T3 [get_ports {Sel[1]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Sel[1]}]
 set_property PACKAGE_PIN T2 [get_ports {SS}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {SS}]
 set_property PACKAGE_PIN R3 [get_ports {DIO}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {DIO}]

# LEDs
set_property PACKAGE_PIN P1 [get_ports {Carryout}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Carryout}]
set_property PACKAGE_PIN L1 [get_ports {Overflow}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Overflow}]


#7 segment display
 set_property PACKAGE_PIN W7 [get_ports {Seg7[0]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[0]}]
 set_property PACKAGE_PIN W6 [get_ports {Seg7[1]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[1]}]
 set_property PACKAGE_PIN U8 [get_ports {Seg7[2]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[2]}]
 set_property PACKAGE_PIN V8 [get_ports {Seg7[3]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[3]}]
 set_property PACKAGE_PIN U5 [get_ports {Seg7[4]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[4]}]
 set_property PACKAGE_PIN V5 [get_ports {Seg7[5]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[5]}]
 set_property PACKAGE_PIN U7 [get_ports {Seg7[6]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[6]}]

 set_property PACKAGE_PIN U2 [get_ports {LED[0]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
 set_property PACKAGE_PIN U4 [get_ports {LED[1]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
 set_property PACKAGE_PIN V4 [get_ports {LED[2]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
 set_property PACKAGE_PIN W4 [get_ports {LED[3]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]