# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk_100Mhz]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk_100Mhz]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk_100Mhz]
	
#7 segment display
 set_property PACKAGE_PIN W7 [get_ports {Seg7[0]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[0]}]
 set_property PACKAGE_PIN W6 [get_ports {Seg7[1]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[1]}]
 set_property PACKAGE_PIN U8 [get_ports {Seg7[2]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[2]}]
 set_property PACKAGE_PIN V8 [get_ports {Seg7[3]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[3]}]
 set_property PACKAGE_PIN U5 [get_ports {Seg7[4]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[4]}]
 set_property PACKAGE_PIN V5 [get_ports {Seg7[5]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[5]}]
 set_property PACKAGE_PIN U7 [get_ports {Seg7[6]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[6]}]

 set_property PACKAGE_PIN U2 [get_ports {LED[0]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
 set_property PACKAGE_PIN U4 [get_ports {LED[1]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
 set_property PACKAGE_PIN V4 [get_ports {LED[2]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
 set_property PACKAGE_PIN W4 [get_ports {LED[3]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]

# Switches
 set_property PACKAGE_PIN V17 [get_ports {RESET}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {RESET}]
 set_property PACKAGE_PIN V16 [get_ports {DIR}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {DIR}]