# Switches
 set_property PACKAGE_PIN V17 [get_ports {Din0[0]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Din0[0]}]
 set_property PACKAGE_PIN V16 [get_ports {Din0[1]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Din0[1]}]
 set_property PACKAGE_PIN W16 [get_ports {Din0[2]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Din0[2]}]
 set_property PACKAGE_PIN W17 [get_ports {Din0[3]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Din0[3]}]
set_property PACKAGE_PIN W15 [get_ports {Din1[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din1[0]}]
set_property PACKAGE_PIN V15 [get_ports {Din1[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din1[1]}]
set_property PACKAGE_PIN W14 [get_ports {Din1[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din1[2]}]
set_property PACKAGE_PIN W13 [get_ports {Din1[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din1[3]}]
set_property PACKAGE_PIN V2 [get_ports {Din2[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din2[0]}]
set_property PACKAGE_PIN T3 [get_ports {Din2[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din2[1]}]
set_property PACKAGE_PIN T2 [get_ports {Din2[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din2[2]}]
set_property PACKAGE_PIN R3 [get_ports {Din2[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din2[3]}]
set_property PACKAGE_PIN W2 [get_ports {Din3[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din3[0]}]
set_property PACKAGE_PIN U1 [get_ports {Din3[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din3[1]}]
set_property PACKAGE_PIN T1 [get_ports {Din3[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din3[2]}]
set_property PACKAGE_PIN R2 [get_ports {Din3[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Din3[3]}]

#7 segment display
 set_property PACKAGE_PIN W7 [get_ports {Seg7[0]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[0]}]
 set_property PACKAGE_PIN W6 [get_ports {Seg7[1]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[1]}]
 set_property PACKAGE_PIN U8 [get_ports {Seg7[2]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[2]}]
 set_property PACKAGE_PIN V8 [get_ports {Seg7[3]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[3]}]
 set_property PACKAGE_PIN U5 [get_ports {Seg7[4]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[4]}]
 set_property PACKAGE_PIN V5 [get_ports {Seg7[5]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[5]}]
 set_property PACKAGE_PIN U7 [get_ports {Seg7[6]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {Seg7[6]}]

 set_property PACKAGE_PIN U2 [get_ports {LED[0]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
 set_property PACKAGE_PIN U4 [get_ports {LED[1]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
 set_property PACKAGE_PIN V4 [get_ports {LED[2]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
 set_property PACKAGE_PIN W4 [get_ports {LED[3]}]					
 	set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]

#Buttons Sel
set_property PACKAGE_PIN U18 [get_ports {Sel[0]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {Sel[0]}]
set_property PACKAGE_PIN T18 [get_ports {Sel[1]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {Sel[1]}]